# Generated by Django 4.2.6 on 2024-02-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default=12, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(default='VAV/media/profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
