# Generated by Django 4.2.6 on 2024-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VAV', '0002_userdetails_password_alter_userdetails_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email_id',
            field=models.EmailField(max_length=200),
        ),
    ]
