# Generated by Django 5.0.2 on 2024-03-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpCal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryinfo',
            name='userId',
        ),
    ]
