# Generated by Django 5.0.4 on 2024-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpCal', '0002_remove_categoryinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expdetails',
            name='additional_info',
            field=models.TextField(default='---', max_length=1000),
        ),
    ]
